# Copyright (C) 2018 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/quanta/narnia/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/quanta/narnia/proprietary/bin/6620_launcher:system/bin/6620_launcher \
    vendor/quanta/narnia/proprietary/bin/6620_wmt_concurrency:system/bin/6620_wmt_concurrency \
    vendor/quanta/narnia/proprietary/bin/6620_wmt_lpbk:system/bin/6620_wmt_lpbk \
    vendor/quanta/narnia/proprietary/bin/MtkCodecService:system/bin/MtkCodecService \
    vendor/quanta/narnia/proprietary/bin/akmd09911:system/bin/akmd09911 \
    vendor/quanta/narnia/proprietary/bin/akmd8963:system/bin/akmd8963 \
    vendor/quanta/narnia/proprietary/bin/audiocmdservice_atci:system/bin/audiocmdservice_atci \
    vendor/quanta/narnia/proprietary/bin/guiext-server:system/bin/guiext-server \
    vendor/quanta/narnia/proprietary/bin/msensord:system/bin/msensord \
    vendor/quanta/narnia/proprietary/bin/nvram_agent_binder:system/bin/nvram_agent_binder \
    vendor/quanta/narnia/proprietary/bin/nvram_daemon:system/bin/nvram_daemon \
    vendor/quanta/narnia/proprietary/bin/pq:system/bin/pq \
    vendor/quanta/narnia/proprietary/bin/wmt_loader:system/bin/wmt_loader \
    vendor/quanta/narnia/proprietary/etc/bluetooth/auto_pair_blacklist.conf:system/etc/bluetooth/auto_pair_blacklist.conf \
    vendor/quanta/narnia/proprietary/etc/bluetooth/auto_pair_devlist.conf:system/etc/bluetooth/auto_pair_devlist.conf \
    vendor/quanta/narnia/proprietary/etc/bluetooth/bt_stack.conf:system/etc/bluetooth/bt_stack.conf \
    vendor/quanta/narnia/proprietary/etc/clatd.conf:system/etc/clatd.conf \
    vendor/quanta/narnia/proprietary/etc/custom.conf:system/etc/custom.conf \
    vendor/quanta/narnia/proprietary/etc/dhcpcd/dhcpcd-hooks/20-dns.conf:system/etc/dhcpcd/dhcpcd-hooks/20-dns.conf \
    vendor/quanta/narnia/proprietary/etc/dhcpcd/dhcpcd-hooks/95-configured:system/etc/dhcpcd/dhcpcd-hooks/95-configured \
    vendor/quanta/narnia/proprietary/etc/dhcpcd/dhcpcd-run-hooks:system/etc/dhcpcd/dhcpcd-run-hooks \
    vendor/quanta/narnia/proprietary/etc/factory.ini:system/etc/factory.ini \
    vendor/quanta/narnia/proprietary/etc/firmware/ROMv2_patch_1_0_hdr.bin:system/etc/firmware/ROMv2_patch_1_0_hdr.bin \
    vendor/quanta/narnia/proprietary/etc/firmware/ROMv2_patch_1_1_hdr.bin:system/etc/firmware/ROMv2_patch_1_1_hdr.bin \
    vendor/quanta/narnia/proprietary/etc/firmware/S_ANDRO_SFL.ini:system/etc/firmware/S_ANDRO_SFL.ini \
    vendor/quanta/narnia/proprietary/etc/firmware/WIFI_RAM_CODE_8127:system/etc/firmware/WIFI_RAM_CODE_8127 \
    vendor/quanta/narnia/proprietary/etc/firmware/WMT_SOC.cfg:system/etc/firmware/WMT_SOC.cfg \
    vendor/quanta/narnia/proprietary/etc/firmware/mt6627/mt6627_fm_v1_coeff.bin:system/etc/firmware/mt6627/mt6627_fm_v1_coeff.bin \
    vendor/quanta/narnia/proprietary/etc/firmware/mt6627/mt6627_fm_v1_patch.bin:system/etc/firmware/mt6627/mt6627_fm_v1_patch.bin \
    vendor/quanta/narnia/proprietary/etc/firmware/mt6627/mt6627_fm_v2_coeff.bin:system/etc/firmware/mt6627/mt6627_fm_v2_coeff.bin \
    vendor/quanta/narnia/proprietary/etc/firmware/mt6627/mt6627_fm_v2_patch.bin:system/etc/firmware/mt6627/mt6627_fm_v2_patch.bin \
    vendor/quanta/narnia/proprietary/etc/firmware/mt6627/mt6627_fm_v3_coeff.bin:system/etc/firmware/mt6627/mt6627_fm_v3_coeff.bin \
    vendor/quanta/narnia/proprietary/etc/firmware/mt6627/mt6627_fm_v3_patch.bin:system/etc/firmware/mt6627/mt6627_fm_v3_patch.bin \
    vendor/quanta/narnia/proprietary/etc/firmware/mt6627/mt6627_fm_v4_coeff.bin:system/etc/firmware/mt6627/mt6627_fm_v4_coeff.bin \
    vendor/quanta/narnia/proprietary/etc/firmware/mt6627/mt6627_fm_v4_patch.bin:system/etc/firmware/mt6627/mt6627_fm_v4_patch.bin \
    vendor/quanta/narnia/proprietary/etc/firmware/mt6627/mt6627_fm_v5_coeff.bin:system/etc/firmware/mt6627/mt6627_fm_v5_coeff.bin \
    vendor/quanta/narnia/proprietary/etc/firmware/mt6627/mt6627_fm_v5_patch.bin:system/etc/firmware/mt6627/mt6627_fm_v5_patch.bin \
    vendor/quanta/narnia/proprietary/etc/fmr/mt6627_fm_cust.cfg:system/etc/fmr/mt6627_fm_cust.cfg \
    vendor/quanta/narnia/proprietary/etc/mtklog-config.prop:system/etc/mtklog-config.prop \
    vendor/quanta/narnia/proprietary/etc/wide-dhcpv6/dhcp6c.conf:system/etc/wide-dhcpv6/dhcp6c.conf \
    vendor/quanta/narnia/proprietary/etc/wide-dhcpv6/dhcp6c.script:system/etc/wide-dhcpv6/dhcp6c.script \
    vendor/quanta/narnia/proprietary/etc/wide-dhcpv6/dhcp6cDNS.conf:system/etc/wide-dhcpv6/dhcp6cDNS.conf \
    vendor/quanta/narnia/proprietary/etc/wide-dhcpv6/dhcp6cctlkey:system/etc/wide-dhcpv6/dhcp6cctlkey \
    vendor/quanta/narnia/proprietary/etc/wide-dhcpv6/dhcp6s.conf:system/etc/wide-dhcpv6/dhcp6s.conf \
    vendor/quanta/narnia/proprietary/lib/egl/egl.cfg:system/lib/egl/egl.cfg \
    vendor/quanta/narnia/proprietary/lib/egl/libEGL_mali.so:system/lib/egl/libEGL_mali.so \
    vendor/quanta/narnia/proprietary/lib/egl/libGLESv1_CM_mali.so:system/lib/egl/libGLESv1_CM_mali.so \
    vendor/quanta/narnia/proprietary/lib/egl/libGLESv2_mali.so:system/lib/egl/libGLESv2_mali.so \
    vendor/quanta/narnia/proprietary/lib/hw/audio.primary.mt8127.so:system/lib/hw/audio.primary.mt8127.so \
    vendor/quanta/narnia/proprietary/lib/hw/camera.mt8127.so:system/lib/hw/camera.mt8127.so \
    vendor/quanta/narnia/proprietary/lib/hw/gps.default.so:system/lib/hw/gps.default.so \
    vendor/quanta/narnia/proprietary/lib/hw/gralloc.mt8127.so:system/lib/hw/gralloc.mt8127.so \
    vendor/quanta/narnia/proprietary/lib/hw/hwcomposer.mt8127.so:system/lib/hw/hwcomposer.mt8127.so \
    vendor/quanta/narnia/proprietary/lib/hw/sensors.mt8127.so:system/lib/hw/sensors.mt8127.so \
    vendor/quanta/narnia/proprietary/lib/lib3a.so:system/lib/lib3a.so \
    vendor/quanta/narnia/proprietary/lib/libBnMtkCodec.so:system/lib/libBnMtkCodec.so \
    vendor/quanta/narnia/proprietary/lib/libGdmaScalerPipe.so:system/lib/libGdmaScalerPipe.so \
    vendor/quanta/narnia/proprietary/lib/libJpgDecPipe.so:system/lib/libJpgDecPipe.so \
    vendor/quanta/narnia/proprietary/lib/libJpgEncPipe.so:system/lib/libJpgEncPipe.so \
    vendor/quanta/narnia/proprietary/lib/libMali.so:system/lib/libMali.so \
    vendor/quanta/narnia/proprietary/lib/libSwJpgCodec.so:system/lib/libSwJpgCodec.so \
    vendor/quanta/narnia/proprietary/lib/lib_uree_mtk_crypto.so:system/lib/lib_uree_mtk_crypto.so \
    vendor/quanta/narnia/proprietary/lib/lib_uree_mtk_video_secure_al.so:system/lib/lib_uree_mtk_video_secure_al.so \
    vendor/quanta/narnia/proprietary/lib/libaed.so:system/lib/libaed.so \
    vendor/quanta/narnia/proprietary/lib/libaudio-resampler.so:system/lib/libaudio-resampler.so \
    vendor/quanta/narnia/proprietary/lib/libaudiocompensationfilter.so:system/lib/libaudiocompensationfilter.so \
    vendor/quanta/narnia/proprietary/lib/libaudiocomponentengine.so:system/lib/libaudiocomponentengine.so \
    vendor/quanta/narnia/proprietary/lib/libaudiocustparam.so:system/lib/libaudiocustparam.so \
    vendor/quanta/narnia/proprietary/lib/libaudiodcrflt.so:system/lib/libaudiodcrflt.so \
    vendor/quanta/narnia/proprietary/lib/libaudiomtkdcremoval.so:system/lib/libaudiomtkdcremoval.so \
    vendor/quanta/narnia/proprietary/lib/libaudiosetting.so:system/lib/libaudiosetting.so \
    vendor/quanta/narnia/proprietary/lib/libbessound_hd_mtk.so:system/lib/libbessound_hd_mtk.so \
    vendor/quanta/narnia/proprietary/lib/libblisrc.so:system/lib/libblisrc.so \
    vendor/quanta/narnia/proprietary/lib/libblisrc32.so:system/lib/libblisrc32.so \
    vendor/quanta/narnia/proprietary/lib/libbluetooth_mtk.so:system/lib/libbluetooth_mtk.so \
    vendor/quanta/narnia/proprietary/lib/libbluetooth_relayer.so:system/lib/libbluetooth_relayer.so \
    vendor/quanta/narnia/proprietary/lib/libbluetoothdrv.so:system/lib/libbluetoothdrv.so \
    vendor/quanta/narnia/proprietary/lib/libbluetoothem_mtk.so:system/lib/libbluetoothem_mtk.so \
    vendor/quanta/narnia/proprietary/lib/libbwc.so:system/lib/libbwc.so \
    vendor/quanta/narnia/proprietary/lib/libcam.camadapter.so:system/lib/libcam.camadapter.so \
    vendor/quanta/narnia/proprietary/lib/libcam.campipe.so:system/lib/libcam.campipe.so \
    vendor/quanta/narnia/proprietary/lib/libcam.camshot.so:system/lib/libcam.camshot.so \
    vendor/quanta/narnia/proprietary/lib/libcam.client.so:system/lib/libcam.client.so \
    vendor/quanta/narnia/proprietary/lib/libcam.device1.so:system/lib/libcam.device1.so \
    vendor/quanta/narnia/proprietary/lib/libcam.exif.so:system/lib/libcam.exif.so \
    vendor/quanta/narnia/proprietary/lib/libcam.paramsmgr.so:system/lib/libcam.paramsmgr.so \
    vendor/quanta/narnia/proprietary/lib/libcam.utils.sensorlistener.so:system/lib/libcam.utils.sensorlistener.so \
    vendor/quanta/narnia/proprietary/lib/libcam.utils.so:system/lib/libcam.utils.so \
    vendor/quanta/narnia/proprietary/lib/libcam_hwutils.so:system/lib/libcam_hwutils.so \
    vendor/quanta/narnia/proprietary/lib/libcam_mmp.so:system/lib/libcam_mmp.so \
    vendor/quanta/narnia/proprietary/lib/libcam_platform.so:system/lib/libcam_platform.so \
    vendor/quanta/narnia/proprietary/lib/libcam_utils.so:system/lib/libcam_utils.so \
    vendor/quanta/narnia/proprietary/lib/libcamalgo.so:system/lib/libcamalgo.so \
    vendor/quanta/narnia/proprietary/lib/libcamdrv.so:system/lib/libcamdrv.so \
    vendor/quanta/narnia/proprietary/lib/libcamera_client_mtk.so:system/lib/libcamera_client_mtk.so \
    vendor/quanta/narnia/proprietary/lib/libcameraanalyzer.so:system/lib/libcameraanalyzer.so \
    vendor/quanta/narnia/proprietary/lib/libcameracustom.so:system/lib/libcameracustom.so \
    vendor/quanta/narnia/proprietary/lib/libcustom_nvram.so:system/lib/libcustom_nvram.so \
    vendor/quanta/narnia/proprietary/lib/libcvsd_mtk.so:system/lib/libcvsd_mtk.so \
    vendor/quanta/narnia/proprietary/lib/libdrmmtkutil.so:system/lib/libdrmmtkutil.so \
    vendor/quanta/narnia/proprietary/lib/libdrmmtkwhitelist.so:system/lib/libdrmmtkwhitelist.so \
    vendor/quanta/narnia/proprietary/lib/libem_support_jni.so:system/lib/libem_support_jni.so \
    vendor/quanta/narnia/proprietary/lib/libfeatureio.so:system/lib/libfeatureio.so \
    vendor/quanta/narnia/proprietary/lib/libfile_op.so:system/lib/libfile_op.so \
    vendor/quanta/narnia/proprietary/lib/libfmjni.so:system/lib/libfmjni.so \
    vendor/quanta/narnia/proprietary/lib/libgralloc_extra.so:system/lib/libgralloc_extra.so \
    vendor/quanta/narnia/proprietary/lib/libgui_ext.so:system/lib/libgui_ext.so \
    vendor/quanta/narnia/proprietary/lib/libhwm.so:system/lib/libhwm.so \
    vendor/quanta/narnia/proprietary/lib/libimageio.so:system/lib/libimageio.so \
    vendor/quanta/narnia/proprietary/lib/libimageio_plat_drv.so:system/lib/libimageio_plat_drv.so \
    vendor/quanta/narnia/proprietary/lib/libion.so:system/lib/libion.so \
    vendor/quanta/narnia/proprietary/lib/libion_mtk.so:system/lib/libion_mtk.so \
    vendor/quanta/narnia/proprietary/lib/libm4u.so:system/lib/libm4u.so \
    vendor/quanta/narnia/proprietary/lib/libmatv_cust.so:system/lib/libmatv_cust.so \
    vendor/quanta/narnia/proprietary/lib/libmemtrack.so:system/lib/libmemtrack.so \
    vendor/quanta/narnia/proprietary/lib/libmhalImageCodec.so:system/lib/libmhalImageCodec.so \
    vendor/quanta/narnia/proprietary/lib/libmmprofile.so:system/lib/libmmprofile.so \
    vendor/quanta/narnia/proprietary/lib/libmnl.so:system/lib/libmnl.so \
    vendor/quanta/narnia/proprietary/lib/libmpo.so:system/lib/libmpo.so \
    vendor/quanta/narnia/proprietary/lib/libmpodecoder.so:system/lib/libmpodecoder.so \
    vendor/quanta/narnia/proprietary/lib/libmpoencoder.so:system/lib/libmpoencoder.so \
    vendor/quanta/narnia/proprietary/lib/libmsbc_mtk.so:system/lib/libmsbc_mtk.so \
    vendor/quanta/narnia/proprietary/lib/libmtcloader.so:system/lib/libmtcloader.so \
    vendor/quanta/narnia/proprietary/lib/libmtk_drvb.so:system/lib/libmtk_drvb.so \
    vendor/quanta/narnia/proprietary/lib/libmtk_mali_user.so:system/lib/libmtk_mali_user.so \
    vendor/quanta/narnia/proprietary/lib/libmtk_mmutils.so:system/lib/libmtk_mmutils.so \
    vendor/quanta/narnia/proprietary/lib/libmtkjpeg.so:system/lib/libmtkjpeg.so \
    vendor/quanta/narnia/proprietary/lib/libmtklimiter.so:system/lib/libmtklimiter.so \
    vendor/quanta/narnia/proprietary/lib/libmtkplayer.so:system/lib/libmtkplayer.so \
    vendor/quanta/narnia/proprietary/lib/libmtkshifter.so:system/lib/libmtkshifter.so \
    vendor/quanta/narnia/proprietary/lib/libnvram.so:system/lib/libnvram.so \
    vendor/quanta/narnia/proprietary/lib/libnvram_daemon_callback.so:system/lib/libnvram_daemon_callback.so \
    vendor/quanta/narnia/proprietary/lib/libnvram_platform.so:system/lib/libnvram_platform.so \
    vendor/quanta/narnia/proprietary/lib/libnvram_sec.so:system/lib/libnvram_sec.so \
    vendor/quanta/narnia/proprietary/lib/libnvramagentclient.so:system/lib/libnvramagentclient.so \
    vendor/quanta/narnia/proprietary/lib/libperfservicenative.so:system/lib/libperfservicenative.so \
    vendor/quanta/narnia/proprietary/lib/libshowlogo.so:system/lib/libshowlogo.so \
    vendor/quanta/narnia/proprietary/lib/libspeech_enh_lib.so:system/lib/libspeech_enh_lib.so \
    vendor/quanta/narnia/proprietary/lib/libstagefright_memutil.so:system/lib/libstagefright_memutil.so \
    vendor/quanta/narnia/proprietary/lib/libstagefrighthw.so:system/lib/libstagefrighthw.so \
    vendor/quanta/narnia/proprietary/lib/libstlport.so:system/lib/libstlport.so \
    vendor/quanta/narnia/proprietary/lib/libtz_uree.so:system/lib/libtz_uree.so \
    vendor/quanta/narnia/proprietary/lib/libui_ext.so:system/lib/libui_ext.so \
    vendor/quanta/narnia/proprietary/lib/liburee_meta_drmkeyinstall_v2.so:system/lib/liburee_meta_drmkeyinstall_v2.so \
    vendor/quanta/narnia/proprietary/lib/libvcodec_utility.so:system/lib/libvcodec_utility.so \
    vendor/quanta/narnia/proprietary/vendor/etc/mtk_omx_core.cfg:system/vendor/etc/mtk_omx_core.cfg \
    vendor/quanta/narnia/proprietary/vendor/lib/libClearMotionFW.so:system/vendor/lib/libClearMotionFW.so \
    vendor/quanta/narnia/proprietary/vendor/lib/libHEVCdec_sa.ca7.android.so:system/vendor/lib/libHEVCdec_sa.ca7.android.so \
    vendor/quanta/narnia/proprietary/vendor/lib/libMtkOmxCore.so:system/vendor/lib/libMtkOmxCore.so \
    vendor/quanta/narnia/proprietary/vendor/lib/libMtkOmxVdecEx.so:system/vendor/lib/libMtkOmxVdecEx.so \
    vendor/quanta/narnia/proprietary/vendor/lib/libMtkOmxVenc.so:system/vendor/lib/libMtkOmxVenc.so \
    vendor/quanta/narnia/proprietary/vendor/lib/libWVStreamControlAPI_L3.so:system/vendor/lib/libWVStreamControlAPI_L3.so \
    vendor/quanta/narnia/proprietary/vendor/lib/libh264enc_sa.ca7.so:system/vendor/lib/libh264enc_sa.ca7.so \
    vendor/quanta/narnia/proprietary/vendor/lib/libh264enc_sb.ca7.so:system/vendor/lib/libh264enc_sb.ca7.so \
    vendor/quanta/narnia/proprietary/vendor/lib/libmp4enc_sa.ca7.so:system/vendor/lib/libmp4enc_sa.ca7.so \
    vendor/quanta/narnia/proprietary/vendor/lib/libmp4enc_xa.ca7.so:system/vendor/lib/libmp4enc_xa.ca7.so \
    vendor/quanta/narnia/proprietary/vendor/lib/librrc.so:system/vendor/lib/librrc.so \
    vendor/quanta/narnia/proprietary/vendor/lib/libvc1dec_sa.ca7.so:system/vendor/lib/libvc1dec_sa.ca7.so \
    vendor/quanta/narnia/proprietary/vendor/lib/libvcodec_oal.so:system/vendor/lib/libvcodec_oal.so \
    vendor/quanta/narnia/proprietary/vendor/lib/libvcodecdrv.so:system/vendor/lib/libvcodecdrv.so \
    vendor/quanta/narnia/proprietary/vendor/lib/libvp8dec_sa.ca7.so:system/vendor/lib/libvp8dec_sa.ca7.so \
    vendor/quanta/narnia/proprietary/vendor/lib/libvp8enc_sa.ca7.so:system/vendor/lib/libvp8enc_sa.ca7.so \
    vendor/quanta/narnia/proprietary/vendor/lib/libvp9dec_sa.ca7.so:system/vendor/lib/libvp9dec_sa.ca7.so \
    vendor/quanta/narnia/proprietary/vendor/lib/libwvdrm_L3.so:system/vendor/lib/libwvdrm_L3.so \
    vendor/quanta/narnia/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
    vendor/quanta/narnia/proprietary/vendor/media/LMspeed_508.emd:system/vendor/media/LMspeed_508.emd \
    vendor/quanta/narnia/proprietary/vendor/media/PFFprec_600.emd:system/vendor/media/PFFprec_600.emd \
    vendor/quanta/narnia/proprietary/xbin/mnld:system/xbin/mnld

PRODUCT_PACKAGES += \
    libdpframework
